# This config is focused on classified names.
#
# When a new client is spawned, it checks its name against
# any of the classifiers.  If there's a match, it will use
# the name specified.  If not, the desktop name will be 
# a space separated string of opened clients.  All empty 
# desktops will use the constant name

remove-empty = true
append-when-occupied = true
renamers = ["classified", "client", "constant"]

[names]
constant = ""

[[names.classified]]
"web" = ["Chromium", "Firefox"]

[[names.classified]]
"" = ["Termite", "Alacritty", "URxvt"]

[[names.classified]]
"" = ["Steam", "Dolphin-emu"]

[[names.classified]]
"" = ["discord"]